[package]
name = "superdev-fellow"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
base64 = "0.22.1"
bs58 = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.140"
solana-sdk = "2.3.1"
tokio = "1.45.1"
